apiVersion: apps/v1
kind: Deployment
metadata:
  name: buryads-ui-next
  labels:
    app: buryads-ui-next
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buryads-ui-next
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: buryads-ui-next
    spec:
      containers:
        - name: buryads-ui-next
          image: <IMAGE>
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://tt.buryads.com"
          startupProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: buryads-ui-next-service
  namespace: applications
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: buryads-ui-next
---
apiVersion: v1
kind: Service
metadata:
  name: buryads-ui-next-service-proxy
  namespace: default
spec:
  type: ExternalName
  externalName: buryads-ui-next-service.applications.svc.cluster.local
