version: "2"

services:
  nginx:
    image: nginx:1.17.0
    depends_on:
      - app
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
    networks:
      - nginx-proxy-network
      - server

  app:
    image: node:14.17.4-buster
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html"
    working_dir: /var/www/html
    command: npm run docker-start
    networks:
      - server

networks:
  server:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
