version: "2"

services:
  nginx:
    image: nginx:1.17.0
    depends_on:
      - app
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html:ro"
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
    networks:
      - nginx-proxy-network
      - server

  app:
    build: ../
    restart: "${RESTART_TYPE}"
    env_file:
      - .env
    networks:
      - server

networks:
  server:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
