version: "3.9"

services:
  nginx:
    image: nginx:1.17.0
    depends_on:
      - app
    restart: "${RESTART_TYPE}"
    volumes:
      - "${APP_DIR}:/var/www/html:ro"∑∑
      - "${NGINX_CONF_DIR}:/etc/nginx/conf.d"
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
    networks:
      - nginx-proxy-network
      - server

  app:
    build: ../
    restart: "${RESTART_TYPE}"
    env_file:
      - .env
    networks:
      - server

  dev:
    image: node:14.17.4-buster
    profiles:
      - dev
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - server
      - nginx-proxy-network
    command: npm run dev

networks:
  server:
  nginx-proxy-network:
    external:
      name: reverseproxy_default
